services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        gem install webrick &&
        jekyll serve --watch --drafts --host 0.0.0.0"
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
